#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

prefix="src" # Replace with your desired prefix

# Get the list of staged files
staged_files=$(git diff --name-only --cached)
exclude_files=("operations.json" "example.json" "schema.json")

# Iterate through the staged files and filter by prefix
for file in $staged_files; do
    filename=$(basename "$file")
  # Check if the filename is not in the exclude list
  if [[ $file == $prefix* && ! "${exclude_files[@]}" =~ "${filename}" ]]; then
    node ./scripts/validateSchema.js $file
  fi
done
# exit 1
