name: CI build

on: 
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  pull_request_review:
    types:
      - submitted

env:
  EMARSYS_USERNAME: ${{ secrets.EMARSYS_USERNAME }}
  EMARSYS_SECRET: ${{ secrets.EMARSYS_SECRET }}

permissions:
  contents: read
  id-token: write
  actions: read


jobs:
  set:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lessonnine'

      - name: yarn install
        run: yarn install

      - id: list_changes
        run: echo ::set-output name=matrix::$(yarn --silent changes A ${{github.sha}} --out json)
  
  build-slices:
    needs: [set]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.set.outputs.matrix) }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lessonnine'

      - name: yarn install
        run: yarn install

      - name: Provision new resource
        id: create_resource
        # if: |
        #     github.event.review.state == 'approved' &&
        #     github.event.pull_request.base.ref == 'main'
        run: |
            response=$(yarn --silent create_resource ${{matrix.files}})
            echo "::set-output name=response::'$response'"
      
      - name: Commit new resource
        # if: |
        #   github.event.review.state == 'approved' &&
        #   github.event.pull_request.base.ref == 'main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          yarn update_resource_config ${{matrix.files}} ${{ steps.create_resource.outputs.response }}
          git add ${{matrix.files}}
          git commit -m "OPS-000: Update new resource configureation ${{matrix.files}}"
          git push origin ${{ github.event.pull_request.head.ref }}
  
  build:
    needs: [build-slices]
    runs-on: ubuntu-latest
    steps:
      - name: Job for branch status check
        run: echo Build complete
