name: Check Build status

on:
        workflow_run:
                workflows: ["CD Provision (Create resources)","CD Provision (Delete resources)"]
                types: [completed]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Check Build status
          uses: actions/github-script@v3
          with:
            script: |
                    const conclusion = github.event.workflow_run.conclusion;
                    const status = conclusion === 'success' ? 'passing' : 'failing';
                    const body = `Build is ${status}`;
                    if (status === 'failing') {
                      throw new Error(body);
                    } else {
                      console.log(body);
                    } 