name: Testing
 
on: 
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
    paths:
      - 'src/**'

permissions:
  contents: read
  id-token: write
  actions: read


jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Nodejs
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lessonnine'

      - name: yarn install
        run: yarn install

      - name: Echo User
        run: echo ${{toJson(github.event.pull_request.head.user)}}

      - name: Validate Files Changes
        if: github.event.pull_request.head.user.login != 'github-actions[bot]'
        run: yarn validate_changes:head_main ${{github.event.pull_request.head.sha}}

      - name: Validate new resources Schema
        run: yarn validate_schema $(yarn --silent changes A ${{github.event.pull_request.head.sha}})

